{
 "title": "Rate Limter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "CPU (4vCPU)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 * avg(1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory (8GB)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[1m]) + avg_over_time(node_memory_Cached_bytes[10m]) + avg_over_time(node_memory_Buffers_bytes[1m])) / avg_over_time(node_memory_MemTotal_bytes[1m])))"
    }
   ]
  },
  {
   "title": "10G Network Saturation",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=\"ens33\"}[1m]) + irate(node_network_transmit_bytes_total{device=\"ens33\"}[1m])) / 10000000000 * 100"
    }
   ]
  },
  {
   "title": "Rate Limited",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sort_desc(topk(5, rate_limited))",
     "legendFormat": "{{source_ip}}"
    }
   ]
  },
  {
   "title": "Packet Drops",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sort_desc(topk(5, rate_limited_drops))",
     "legendFormat": "{{source_ip}}"
    }
   ]
  },
  {
   "title": "Available Tokens (Packet limit)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "bottomk(5, sort(rate_limited_tokens))",
     "legendFormat": "{{source_ip}}"
    }
   ]
  }
 ]
}